# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cosmospy.interfaces.gogo_pb2 as gogo__pb2
import cosmospy.interfaces.any_pb2 as any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x12ibc.core.client.v1\x1a\ngogo.proto\x1a\tany.proto\"\x85\x01\n\x15IdentifiedClientState\x12\'\n\tclient_id\x18\x01 \x01(\tB\x14\xf2\xde\x1f\x10yaml:\"client_id\"\x12\x43\n\x0c\x63lient_state\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\x17\xf2\xde\x1f\x13yaml:\"client_state\"\"\x97\x01\n\x18\x43onsensusStateWithHeight\x12\x30\n\x06height\x18\x01 \x01(\x0b\x32\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00\x12I\n\x0f\x63onsensus_state\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\x1a\xf2\xde\x1f\x16yaml:\"consensus_state\"\"\xa9\x01\n\x15\x43lientConsensusStates\x12\'\n\tclient_id\x18\x01 \x01(\tB\x14\xf2\xde\x1f\x10yaml:\"client_id\"\x12g\n\x10\x63onsensus_states\x18\x02 \x03(\x0b\x32,.ibc.core.client.v1.ConsensusStateWithHeightB\x1f\xf2\xde\x1f\x17yaml:\"consensus_states\"\xc8\xde\x1f\x00\"|\n\x06Height\x12\x33\n\x0frevision_number\x18\x01 \x01(\x04\x42\x1a\xf2\xde\x1f\x16yaml:\"revision_number\"\x12\x33\n\x0frevision_height\x18\x02 \x01(\x04\x42\x1a\xf2\xde\x1f\x16yaml:\"revision_height\":\x08\x88\xa0\x1f\x00\x98\xa0\x1f\x00\"=\n\x06Params\x12\x33\n\x0f\x61llowed_clients\x18\x01 \x03(\tB\x1a\xf2\xde\x1f\x16yaml:\"allowed_clients\"B:Z8github.com/cosmos/ibc-go/v3/modules/core/02-client/typesb\x06proto3')



_IDENTIFIEDCLIENTSTATE = DESCRIPTOR.message_types_by_name['IdentifiedClientState']
_CONSENSUSSTATEWITHHEIGHT = DESCRIPTOR.message_types_by_name['ConsensusStateWithHeight']
_CLIENTCONSENSUSSTATES = DESCRIPTOR.message_types_by_name['ClientConsensusStates']
_HEIGHT = DESCRIPTOR.message_types_by_name['Height']
_PARAMS = DESCRIPTOR.message_types_by_name['Params']
IdentifiedClientState = _reflection.GeneratedProtocolMessageType('IdentifiedClientState', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFIEDCLIENTSTATE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.IdentifiedClientState)
  })
_sym_db.RegisterMessage(IdentifiedClientState)

ConsensusStateWithHeight = _reflection.GeneratedProtocolMessageType('ConsensusStateWithHeight', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSSTATEWITHHEIGHT,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.ConsensusStateWithHeight)
  })
_sym_db.RegisterMessage(ConsensusStateWithHeight)

ClientConsensusStates = _reflection.GeneratedProtocolMessageType('ClientConsensusStates', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCONSENSUSSTATES,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.ClientConsensusStates)
  })
_sym_db.RegisterMessage(ClientConsensusStates)

Height = _reflection.GeneratedProtocolMessageType('Height', (_message.Message,), {
  'DESCRIPTOR' : _HEIGHT,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.Height)
  })
_sym_db.RegisterMessage(Height)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:ibc.core.client.v1.Params)
  })
_sym_db.RegisterMessage(Params)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8github.com/cosmos/ibc-go/v3/modules/core/02-client/types'
  _IDENTIFIEDCLIENTSTATE.fields_by_name['client_id']._options = None
  _IDENTIFIEDCLIENTSTATE.fields_by_name['client_id']._serialized_options = b'\362\336\037\020yaml:\"client_id\"'
  _IDENTIFIEDCLIENTSTATE.fields_by_name['client_state']._options = None
  _IDENTIFIEDCLIENTSTATE.fields_by_name['client_state']._serialized_options = b'\362\336\037\023yaml:\"client_state\"'
  _CONSENSUSSTATEWITHHEIGHT.fields_by_name['height']._options = None
  _CONSENSUSSTATEWITHHEIGHT.fields_by_name['height']._serialized_options = b'\310\336\037\000'
  _CONSENSUSSTATEWITHHEIGHT.fields_by_name['consensus_state']._options = None
  _CONSENSUSSTATEWITHHEIGHT.fields_by_name['consensus_state']._serialized_options = b'\362\336\037\026yaml:\"consensus_state\"'
  _CLIENTCONSENSUSSTATES.fields_by_name['client_id']._options = None
  _CLIENTCONSENSUSSTATES.fields_by_name['client_id']._serialized_options = b'\362\336\037\020yaml:\"client_id\"'
  _CLIENTCONSENSUSSTATES.fields_by_name['consensus_states']._options = None
  _CLIENTCONSENSUSSTATES.fields_by_name['consensus_states']._serialized_options = b'\362\336\037\027yaml:\"consensus_states\"\310\336\037\000'
  _HEIGHT.fields_by_name['revision_number']._options = None
  _HEIGHT.fields_by_name['revision_number']._serialized_options = b'\362\336\037\026yaml:\"revision_number\"'
  _HEIGHT.fields_by_name['revision_height']._options = None
  _HEIGHT.fields_by_name['revision_height']._serialized_options = b'\362\336\037\026yaml:\"revision_height\"'
  _HEIGHT._options = None
  _HEIGHT._serialized_options = b'\210\240\037\000\230\240\037\000'
  _PARAMS.fields_by_name['allowed_clients']._options = None
  _PARAMS.fields_by_name['allowed_clients']._serialized_options = b'\362\336\037\026yaml:\"allowed_clients\"'
  _IDENTIFIEDCLIENTSTATE._serialized_start=60
  _IDENTIFIEDCLIENTSTATE._serialized_end=193
  _CONSENSUSSTATEWITHHEIGHT._serialized_start=196
  _CONSENSUSSTATEWITHHEIGHT._serialized_end=347
  _CLIENTCONSENSUSSTATES._serialized_start=350
  _CLIENTCONSENSUSSTATES._serialized_end=519
  _HEIGHT._serialized_start=521
  _HEIGHT._serialized_end=645
  _PARAMS._serialized_start=647
  _PARAMS._serialized_end=708
# @@protoc_insertion_point(module_scope)
